
CERT_VIEW_TOFILE
SELECT cert."CERT_ID",cert."FORMS",cert."UNN",cert."KONTRP",cert."KONTRS",
cert."ADRESS",cert. "POLUCHAT",cert."ADRESSPOL",cert."DATACERT",cert."ISSUEDATE", 
cert."NOMERCERT",cert."EXPERT",cert."NBLANKA",cert."RUKOVOD",cert."TRANSPORT", 
cert."MARSHRUT",cert."OTMETKA",cert."STRANAV",cert."STRANAPR",cert."STATUS",
cert."KOLDOPLIST",cert."FLEXP",cert."UNNEXP",cert."EXPP",cert."EXPS",
cert."EXPADRESS",cert."FLIMP",cert."IMPORTER",cert."ADRESSIMP",cert."FLSEZ",
cert."SEZ",cert."FLSEZREZ",cert."STRANAP",cert."OTD_ID",cert."PARENTNUMBER",
cert."PARENTSTATUS", cert."CODESTRANAV", cert."CODESTRANAPR", cert."CODESTRANAP",
cert."CATEGORY", cert."PARENT_ID",cert."OTD_NAME",cert."OTD_ADDR_INDEX",
cert."OTD_ADDR_CITY",cert."OTD_ADDR_LINE",cert."OTD_ADDR_BUILDING",
a.tovar
FROM CERT_VIEW cert
LEFT JOIN C_PRODUCT_DENORM a on cert.CERT_ID=a.CERT_ID


CERT_VIEW_LOAD_REPORT
SELECT cert."CERT_ID",cert."FORMS",cert."UNN",cert."KONTRP",cert."KONTRS",
cert."ADRESS",cert. "POLUCHAT",cert."ADRESSPOL",cert."DATACERT",cert."ISSUEDATE", 
cert."NOMERCERT",cert."EXPERT",cert."NBLANKA",cert."RUKOVOD",cert."TRANSPORT", 
cert."MARSHRUT",cert."OTMETKA",cert."STRANAV",cert."STRANAPR",cert."STATUS",
cert."KOLDOPLIST",cert."FLEXP",cert."UNNEXP",cert."EXPP",cert."EXPS",
cert."EXPADRESS",cert."FLIMP",cert."IMPORTER",cert."ADRESSIMP",cert."FLSEZ",
cert."SEZ",cert."FLSEZREZ",cert."STRANAP",cert."OTD_ID",cert."PARENTNUMBER",
cert."PARENTSTATUS", cert."CODESTRANAV", cert."CODESTRANAPR", cert."CODESTRANAP",
cert."CATEGORY", cert."PARENT_ID",cert."OTD_NAME",cert."OTD_ADDR_INDEX",
cert."OTD_ADDR_CITY",cert."OTD_ADDR_LINE",cert."OTD_ADDR_BUILDING",
a.tovar, bb.DATE_LOAD 
FROM C_FILES_IN bb
LEFT JOIN CERT_VIEW cert on bb.cert_id = cert.cert_id
LEFT JOIN C_PRODUCT_DENORM a on bb.CERT_ID=a.CERT_ID


CERT_REPORT
select cc."FILE_IN_ID",cc."CERT_ID",cc."NOMERCERT",cc."NBLANKA",cc."DATACERT",cc."ISSUEDATE",cc."EXPERT",cc."DATE_LOAD",cc."OTD_ID", otd_name 
from (select file_in_id, aa.cert_id, nomercert, nblanka, datacert, issuedate, expert, 
DATE_LOAD, otd_id 
from C_FILES_IN aa left join C_CERT bb on aa.cert_id = bb.cert_id) cc 
left join C_OTD dd on cc.otd_id = dd.id;

//  ----------  FILES_IN Indexes --------------------- 
DROP INDEX "BELTPP"."IND_FILES_DATELOAD_ID";
DROP INDEX "BELTPP"."IND_FILES_IN_DATELOAD";
DROP INDEX "BELTPP"."IND_FILES_IN_CERTID";
DROP INDEX "BELTPP"."IND_FILES_IN_ID";

CREATE UNIQUE INDEX "BELTPP"."IND_FILES_DATELOAD_ID" ON "BELTPP"."C_FILES_IN" ("DATE_LOAD", "FILE_IN_ID");
CREATE INDEX "BELTPP"."IND_FILES_IN_DATELOAD" ON "BELTPP"."C_FILES_IN" ("DATE_LOAD");
CREATE INDEX "BELTPP"."IND_FILES_IN_CERTID" ON "BELTPP"."C_FILES_IN" ("CERT_ID");
CREATE UNIQUE INDEX "BELTPP"."IND_FILES_IN_ID" ON "BELTPP"."C_FILES_IN" ("FILE_IN_ID");


//  ----------  C_CERT Indexes ---------------------
DROP INDEX "BELTPP"."CERT_ISSUDATE";
DROP INDEX "BELTPP"."CERT_ISSUEDATE_CERT_ID";
DROP INDEX "BELTPP"."CERT_NBLANKA";
DROP INDEX "BELTPP"."CERT_NBLANKA_CERTID";
DROP INDEX "BELTPP"."CERT_NOMERCERT_CERTID";
DROP INDEX "BELTPP"."CERT_NUMBER_IDX";
DROP INDEX "BELTPP"."CERT_OTDID_CERTID";
DROP INDEX "BELTPP"."CERT_OTD_ID";
DROP INDEX "BELTPP"."CERT_PARENTNUMBER_IDX";

CREATE INDEX "BELTPP"."CERT_ISSUDATE" ON "BELTPP"."C_CERT" ("ISSUEDATE");
CREATE UNIQUE INDEX "BELTPP"."CERT_ISSUEDATE_CERT_ID" ON "BELTPP"."C_CERT" ("ISSUEDATE", "CERT_ID");
CREATE INDEX "BELTPP"."CERT_NBLANKA" ON "BELTPP"."C_CERT" ("NBLANKA");
CREATE UNIQUE INDEX "BELTPP"."CERT_NBLANKA_CERTID" ON "BELTPP"."C_CERT" ("NBLANKA", "CERT_ID");
CREATE UNIQUE INDEX "BELTPP"."CERT_NOMERCERT_CERTID" ON "BELTPP"."C_CERT" ("NOMERCERT", "CERT_ID");
CREATE UNIQUE INDEX "BELTPP"."CERT_NUMBER_IDX" ON "BELTPP"."C_CERT" ("NOMERCERT") ;
CREATE UNIQUE INDEX "BELTPP"."CERT_OTDID_CERTID" ON "BELTPP"."C_CERT" ("OTD_ID", "CERT_ID");
CREATE INDEX "BELTPP"."CERT_OTD_ID" ON "BELTPP"."C_CERT" ("OTD_ID") ;
CREATE INDEX "BELTPP"."CERT_PARENTNUMBER_IDX" ON "BELTPP"."C_CERT" ("PARENTNUMBER");
