--------------------------------------------------------
--  DDL for Table EV_REPORT_ROW
--------------------------------------------------------

  CREATE TABLE "EV_REPORT_ROW" 
   (	"ID_REPORT" NUMBER, 
	"ACTION_CODE" NUMBER, 
	"NUM_PAST" NUMBER DEFAULT 0, 
	"NUM_CURRENT" NUMBER DEFAULT 0, 
	"NUM_RISE" NUMBER DEFAULT 0, 
	"NUM_PERCENT_RISE" NUMBER DEFAULT 0, 
	"MONEY_PAST" NUMBER DEFAULT 0, 
	"MONEY_CURRENT" NUMBER DEFAULT 0, 
	"MONEY_RISE" NUMBER DEFAULT 0, 
	"MONEY_PERCENT_RISE" NUMBER DEFAULT 0, 
	"WEIGHT_FRD" NUMBER DEFAULT 0, 
	"WEIGHT_ALL" NUMBER DEFAULT 0, 
	"ID_ROW" NUMBER
   ) ;
