--------------------------------------------------------
--  Constraints for Table EV_GROUP_VALUE
--------------------------------------------------------

  ALTER TABLE "EV_GROUP_VALUE" ADD CONSTRAINT "GROUP_VALUE_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "EV_GROUP_VALUE" MODIFY ("ID_REPORT" NOT NULL ENABLE);
  ALTER TABLE "EV_GROUP_VALUE" MODIFY ("ID_MARK" NOT NULL ENABLE);
  ALTER TABLE "EV_GROUP_VALUE" MODIFY ("ID_GROUP" NOT NULL ENABLE);
  ALTER TABLE "EV_GROUP_VALUE" MODIFY ("ID" NOT NULL ENABLE);
