ALTER TABLE C_OTD 
 ADD {
    OTD_ADDRESS_INDEX varchar2(15)
    OTD_ADDRESS_CITY varchar2(15)
    OTD_ADDRESS_LINE varchar2(50)
    OTD_ADDRESS_HOME varchar2(10)
    };
 
 ALTER TABLE C_OTD 
    ADD OTD_ADDRESS_EXP date;
   
ALTER TABLE XML_CERT 
   ADD OTD_ID number ;
 
UPDATE XML_CERT 
   SET OTD_ID = 1;

ALTER TABLE C_OTD 
  ADD PRIMARY KEY (otd_id);

  ALTER TABLE XML_CERT
    ADD  FOREIGN KEY
    (otd_id)
    REFERENCES C_OTD (otd_id);
    
GRANT CREATE VIEW TO BELTPP_CERT; 
    
CREATE VIEW CERT_VIEW AS 
  select a.*, B.OTD_NAME, B.OTD_ADDRESS_INDEX, B.OTD_ADDRESS_CITY, B.OTD_ADDRESS_LINE, B.OTD_ADDRESS_HOME 
  from XML_CERT a left join C_OTD b  on  A.OTD_ID = B.OTD_ID;

 