--------------------------------------------------------
--  File created - пятница-Сентябрь-12-2014   
--------------------------------------------------------
-- Unable to render SEQUENCE DDL for object BELTPP.CERT_ID_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE CERT_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.FILE_ID_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE FILE_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.ID_ACTION_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE ID_ACTION_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.ID_PURCHASE_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE ID_PURCHASE_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.ID_REPORT_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE ID_REPORT_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.ID_ROW_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE ID_ROW_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render SEQUENCE DDL for object BELTPP.PRODUCT_ID_SEQ with DBMS_METADATA attempting internal generator.
CREATE SEQUENCE PRODUCT_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20
-- Unable to render TABLE DDL for object BELTPP.C_CERT with DBMS_METADATA attempting internal generator.
CREATE TABLE C_CERT 
(
  CERT_ID NUMBER NOT NULL 
, FORMS VARCHAR2(1000 BYTE) 
, UNN VARCHAR2(1000 BYTE) 
, KONTRP VARCHAR2(1000 BYTE) 
, KONTRS VARCHAR2(1000 BYTE) 
, ADRESS VARCHAR2(1000 BYTE) 
, POLUCHAT VARCHAR2(1000 BYTE) 
, ADRESSPOL VARCHAR2(1000 BYTE) 
, DATACERT VARCHAR2(1000 BYTE) 
, NOMERCERT VARCHAR2(1000 BYTE) 
, EXPERT VARCHAR2(1000 BYTE) 
, NBLANKA VARCHAR2(1000 BYTE) 
, RUKOVOD VARCHAR2(1000 BYTE) 
, TRANSPORT VARCHAR2(1000 BYTE) 
, MARSHRUT VARCHAR2(1000 BYTE) 
, OTMETKA VARCHAR2(1000 BYTE) 
, STRANAV VARCHAR2(1000 BYTE) 
, STRANAPR VARCHAR2(1000 BYTE) 
, STATUS VARCHAR2(1000 BYTE) 
, KOLDOPLIST VARCHAR2(1000 BYTE) 
, FLEXP VARCHAR2(1000 BYTE) 
, UNNEXP VARCHAR2(1000 BYTE) 
, EXPP VARCHAR2(1000 BYTE) 
, EXPS VARCHAR2(1000 BYTE) 
, EXPADRESS VARCHAR2(1000 BYTE) 
, FLIMP VARCHAR2(1000 BYTE) 
, IMPORTER VARCHAR2(1000 BYTE) 
, ADRESSIMP VARCHAR2(1000 BYTE) 
, FLSEZ VARCHAR2(1000 BYTE) 
, SEZ VARCHAR2(1000 BYTE) 
, FLSEZREZ VARCHAR2(1000 BYTE) 
, STRANAP VARCHAR2(1000 BYTE) 
, OTD_ID NUMBER 
, PARENTNUMBER VARCHAR2(50 BYTE) 
, PARENTSTATUS VARCHAR2(80 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 

NOCOMPRESSALTER TABLE C_CERT
ADD CONSTRAINT SYS_C007007 FOREIGN KEY
(
  OTD_ID 
)
REFERENCES C_OTD
(
  ID 
)
ENABLECREATE UNIQUE INDEX CERT_NUMBER_IDX ON C_CERT (NOMERCERT ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX CERT_PARENTNUMBER_IDX ON C_CERT (PARENTNUMBER ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX IDX_DATACERT ON C_CERT (DATACERT ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX SYS_C007001 ON C_CERT (CERT_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE C_CERT
ADD CONSTRAINT SYS_C007001 PRIMARY KEY 
(
  CERT_ID 
)
USING INDEX SYS_C007001
ENABLE
-- Unable to render TABLE DDL for object BELTPP.C_COUNTRY with DBMS_METADATA attempting internal generator.
CREATE TABLE C_COUNTRY 
(
  COUNTRY_ID VARCHAR2(3 BYTE) NOT NULL 
, COUNTRY_NAME VARCHAR2(255 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX SYS_C007006 ON C_COUNTRY (COUNTRY_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE C_COUNTRY
ADD CONSTRAINT SYS_C007006 PRIMARY KEY 
(
  COUNTRY_ID 
)
USING INDEX SYS_C007006
ENABLE
-- Unable to render TABLE DDL for object BELTPP.C_FILES_IN with DBMS_METADATA attempting internal generator.
CREATE TABLE C_FILES_IN 
(
  FILE_IN_ID NUMBER 
, FILE_IN_NAME VARCHAR2(255 BYTE) 
, CERT_ID NUMBER 
, DATE_LOAD DATE 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Unable to render TABLE DDL for object BELTPP.C_FILES_OUT with DBMS_METADATA attempting internal generator.
CREATE TABLE C_FILES_OUT 
(
  FILE_IN_ID NUMBER 
, FILE_IN_NAME VARCHAR2(255 BYTE) 
, CERT_ID NUMBER 
, DATE_LOAD DATE 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Unable to render TABLE DDL for object BELTPP.C_OTD with DBMS_METADATA attempting internal generator.
CREATE TABLE C_OTD 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(255 BYTE) 
, NAME_SYN VARCHAR2(100 BYTE) 
, ADDR_INDEX VARCHAR2(250 BYTE) 
, ADDR_CITY VARCHAR2(250 BYTE) 
, ADDR_LINE VARCHAR2(250 BYTE) 
, ADDR_BUILDING VARCHAR2(250 BYTE) 
, ADDR_OFFICE VARCHAR2(250 BYTE) 
, WORK_PHONE VARCHAR2(50 BYTE) 
, CELL_PHONE VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX SYS_C006997 ON C_OTD (ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE C_OTD
ADD CONSTRAINT SYS_C006997 PRIMARY KEY 
(
  ID 
)
USING INDEX SYS_C006997
ENABLE
-- Unable to render TABLE DDL for object BELTPP.C_PRODUCT with DBMS_METADATA attempting internal generator.
CREATE TABLE C_PRODUCT 
(
  PRODUCT_ID NUMBER NOT NULL 
, CERT_ID NUMBER 
, NUMERATOR VARCHAR2(1000 BYTE) 
, TOVAR VARCHAR2(2200 BYTE) 
, VIDUP VARCHAR2(1000 BYTE) 
, KRITER VARCHAR2(1000 BYTE) 
, VES VARCHAR2(1000 BYTE) 
, SCHET VARCHAR2(1000 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE C_PRODUCT
ADD CONSTRAINT SYS_C007011 FOREIGN KEY
(
  CERT_ID 
)
REFERENCES C_CERT
(
  CERT_ID 
)
ENABLECREATE UNIQUE INDEX SYS_C007010 ON C_PRODUCT (PRODUCT_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE C_PRODUCT
ADD CONSTRAINT SYS_C007010 PRIMARY KEY 
(
  PRODUCT_ID 
)
USING INDEX SYS_C007010
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_ACTION with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_ACTION 
(
  ID NUMBER NOT NULL 
, CODE VARCHAR2(20 BYTE) 
, NAME VARCHAR2(250 BYTE) 
, PARENT VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE INDEX CODE_IND ON EV_ACTION (CODE ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX ID_PK ON EV_ACTION (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_ACTION
ADD CONSTRAINT ID_PK PRIMARY KEY 
(
  ID 
)
USING INDEX ID_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_GROUP with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_GROUP 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX ID_GROUP_PK ON EV_GROUP (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_GROUP
ADD CONSTRAINT ID_GROUP_PK PRIMARY KEY 
(
  ID 
)
USING INDEX ID_GROUP_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_GROUP_ACTION with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_GROUP_ACTION 
(
  ID NUMBER NOT NULL 
, ID_GROUP NUMBER 
, ID_ACTION NUMBER 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE EV_GROUP_ACTION
ADD CONSTRAINT ACTION_FK FOREIGN KEY
(
  ID_ACTION 
)
REFERENCES EV_ACTION
(
  ID 
)
ENABLE
ALTER TABLE EV_GROUP_ACTION
ADD CONSTRAINT GROUP_FK FOREIGN KEY
(
  ID_GROUP 
)
REFERENCES EV_GROUP
(
  ID 
)
ENABLECREATE UNIQUE INDEX GROUP_ACTION_PK ON EV_GROUP_ACTION (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_GROUP_ACTION
ADD CONSTRAINT GROUP_ACTION_PK PRIMARY KEY 
(
  ID 
)
USING INDEX GROUP_ACTION_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_GROUP_VALUE with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_GROUP_VALUE 
(
  ID NUMBER NOT NULL 
, ID_GROUP NUMBER NOT NULL 
, ID_MARK NUMBER NOT NULL 
, ID_REPORT NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE EV_GROUP_VALUE
ADD CONSTRAINT GROUP_GROUP_FK FOREIGN KEY
(
  ID_GROUP 
)
REFERENCES EV_GROUP
(
  ID 
)
ENABLE
ALTER TABLE EV_GROUP_VALUE
ADD CONSTRAINT GROUP_MARK_FK FOREIGN KEY
(
  ID_MARK 
)
REFERENCES EV_REPORT_MARK
(
  ID 
)
ENABLE
ALTER TABLE EV_GROUP_VALUE
ADD CONSTRAINT GROUP_REPORT_FK FOREIGN KEY
(
  ID_REPORT 
)
REFERENCES EV_REPORT
(
  ID 
)
ENABLECREATE UNIQUE INDEX GROUP_VALUE_PK ON EV_GROUP_VALUE (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_GROUP_VALUE
ADD CONSTRAINT GROUP_VALUE_PK PRIMARY KEY 
(
  ID 
)
USING INDEX GROUP_VALUE_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_REPORT with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_REPORT 
(
  ID NUMBER NOT NULL 
, YEAR NUMBER NOT NULL 
, QUARTER NUMBER NOT NULL 
, ID_OFFICE NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE EV_REPORT
ADD CONSTRAINT REPORT_FK_TO_OTD FOREIGN KEY
(
  ID_OFFICE 
)
REFERENCES C_OTD
(
  ID 
)
ENABLECREATE UNIQUE INDEX REPORT_PK ON EV_REPORT (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_REPORT
ADD CONSTRAINT REPORT_PK PRIMARY KEY 
(
  ID 
)
USING INDEX REPORT_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_REPORT_MARK with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_REPORT_MARK 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 BYTE) 
, POSITION NUMBER 
, CODE VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX REPORT_MARK_PK ON EV_REPORT_MARK (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE EV_REPORT_MARK
ADD CONSTRAINT REPORT_MARK_PK PRIMARY KEY 
(
  ID 
)
USING INDEX REPORT_MARK_PK
ENABLE
-- Unable to render TABLE DDL for object BELTPP.EV_REPORT_ROW with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_REPORT_ROW 
(
  ID_REPORT NUMBER NOT NULL 
, ACTION_CODE NUMBER 
, NUM_PAST NUMBER DEFAULT 0 
, NUM_CURRENT NUMBER DEFAULT 0 
, NUM_RISE NUMBER DEFAULT 0 
, NUM_PERCENT_RISE NUMBER DEFAULT 0 
, MONEY_PAST NUMBER DEFAULT 0 
, MONEY_CURRENT NUMBER DEFAULT 0 
, MONEY_RISE NUMBER DEFAULT 0 
, MONEY_PERCENT_RISE NUMBER DEFAULT 0 
, WEIGHT_FRD NUMBER DEFAULT 0 
, WEIGHT_ALL NUMBER DEFAULT 0 
, ID_ROW NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Unable to render TABLE DDL for object BELTPP.EV_REPORT_VALUE with DBMS_METADATA attempting internal generator.
CREATE TABLE EV_REPORT_VALUE 
(
  ID_REPORT NUMBER 
, ID_MARK NUMBER 
, ID_ACTION NUMBER 
, VALUE NUMBER 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Unable to render TABLE DDL for object BELTPP.PCH_COMPANY with DBMS_METADATA attempting internal generator.
CREATE TABLE PCH_COMPANY 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 BYTE) 
, ADDR_CITY VARCHAR2(200 BYTE) 
, ADDR_LINE VARCHAR2(200 BYTE) 
, ADDR_INDEX VARCHAR2(200 BYTE) 
, ADDR_OFFICE VARCHAR2(200 BYTE) 
, ADDR_BUILDING VARCHAR2(200 BYTE) 
, WORK_PHONE VARCHAR2(50 BYTE) 
, CELL_PHONE VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX ID ON PCH_COMPANY (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PCH_COMPANY
ADD CONSTRAINT ID PRIMARY KEY 
(
  ID 
)
USING INDEX ID
ENABLE
-- Unable to render TABLE DDL for object BELTPP.PCH_PRODUCT with DBMS_METADATA attempting internal generator.
CREATE TABLE PCH_PRODUCT 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 BYTE) 
, ID_PARENT NUMBER 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE PCH_PRODUCT
ADD CONSTRAINT FK_ID_PARENT FOREIGN KEY
(
  ID_PARENT 
)
REFERENCES PCH_PRODUCT
(
  ID 
)
ENABLECREATE UNIQUE INDEX ID_PRODUCT ON PCH_PRODUCT (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PCH_PRODUCT
ADD CONSTRAINT ID_PRODUCT PRIMARY KEY 
(
  ID 
)
USING INDEX ID_PRODUCT
ENABLE
-- Unable to render TABLE DDL for object BELTPP.PCH_PURCHASE with DBMS_METADATA attempting internal generator.
CREATE TABLE PCH_PURCHASE 
(
  ID NUMBER NOT NULL 
, ID_PRODUCT NUMBER 
, ID_OTD NUMBER 
, ID_COMPANY NUMBER 
, PRICE NUMBER 
, VOLUME NUMBER 
, UNIT VARCHAR2(50 BYTE) 
, PCHDATE DATE 
, PRODUCTPROPERTY VARCHAR2(1000 BYTE) 
) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE PCH_PURCHASE
ADD CONSTRAINT FK_ID_COMPANY FOREIGN KEY
(
  ID_COMPANY 
)
REFERENCES PCH_COMPANY
(
  ID 
)
ENABLE
ALTER TABLE PCH_PURCHASE
ADD CONSTRAINT FK_ID_OTD FOREIGN KEY
(
  ID_OTD 
)
REFERENCES C_OTD
(
  ID 
)
ENABLE
ALTER TABLE PCH_PURCHASE
ADD CONSTRAINT FK_ID_PRODUCT FOREIGN KEY
(
  ID_PRODUCT 
)
REFERENCES PCH_PRODUCT
(
  ID 
)
ENABLECREATE UNIQUE INDEX ID_PURCHASE ON PCH_PURCHASE (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE PCH_PURCHASE
ADD CONSTRAINT ID_PURCHASE PRIMARY KEY 
(
  ID 
)
USING INDEX ID_PURCHASE
ENABLE
-- Unable to render VIEW DDL for object BELTPP.CERT_CHILD_VIEW with DBMS_METADATA attempting internal generator.
CREATE VIEW CERT_CHILD_VIEW
AS select tt."CERT_ID",tt."FORMS",tt."UNN",tt."KONTRP",tt."KONTRS",tt."ADRESS",tt."POLUCHAT",tt."ADRESSPOL",tt."DATACERT",tt."NOMERCERT",tt."EXPERT",tt."NBLANKA",tt."RUKOVOD",tt."TRANSPORT",tt."MARSHRUT",tt."OTMETKA",tt."STRANAV",tt."STRANAPR",tt."STATUS",tt."KOLDOPLIST",tt."FLEXP",tt."UNNEXP",tt."EXPP",tt."EXPS",tt."EXPADRESS",tt."FLIMP",tt."IMPORTER",tt."ADRESSIMP",tt."FLSEZ",tt."SEZ",tt."FLSEZREZ",tt."STRANAP",tt."OTD_ID",tt."PARENTNUMBER",tt."PARENTSTATUS", bb.nomercert chldnumber, bb.CERT_ID child_id from c_cert tt left join c_cert bb on tt.nomercert = bb.parentnumber
-- Unable to render VIEW DDL for object BELTPP.CERT_VIEW with DBMS_METADATA attempting internal generator.
CREATE VIEW CERT_VIEW
AS select a."CERT_ID",a."FORMS",a."UNN",a."KONTRP",a."KONTRS",a."ADRESS",a."POLUCHAT",a."ADRESSPOL",a."DATACERT",a."NOMERCERT",a."EXPERT",a."NBLANKA",a."RUKOVOD",a."TRANSPORT",a."MARSHRUT",a."OTMETKA",a."STRANAV",a."STRANAPR",a."STATUS",a."KOLDOPLIST",a."FLEXP",a."UNNEXP",a."EXPP",a."EXPS",a."EXPADRESS",a."FLIMP",a."IMPORTER",a."ADRESSIMP",a."FLSEZ",a."SEZ",a."FLSEZREZ",a."STRANAP",a."OTD_ID",a."PARENTNUMBER",a."PARENTSTATUS",a."CHLDNUMBER",a."CHILD_ID", B.NAME otd_name, B.NAME, B.ADDR_INDEX otd_address_index, B.ADDR_CITY, B.ADDR_LINE, B.ADDR_BUILDING
  from CERT_CHILD_VIEW a left join C_OTD b on A.OTD_ID = B.ID
-- Unable to render VIEW DDL for object BELTPP.PCH_PURCHASE_VIEW with DBMS_METADATA attempting internal generator.
CREATE VIEW PCH_PURCHASE_VIEW
AS SELECT a."ID",a."ID_PRODUCT",a."ID_OTD",a."ID_COMPANY",a."PRICE",a."VOLUME",a."UNIT",a."PCHDATE",a."PRODUCTPROPERTY", b.name as company, c.name as product, d.name as department 
FROM PCH_PURCHASE a inner join PCH_COMPANY b on a.id_company = b.id 
                    inner join PCH_PRODUCT c on a.id_product = c.id 
                    inner join C_OTD d on a.id_otd = d.id
-- Unable to render INDEX DDL for object BELTPP.CERT_NUMBER_IDX with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX CERT_NUMBER_IDX ON C_CERT (NOMERCERT ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.CERT_PARENTNUMBER_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX CERT_PARENTNUMBER_IDX ON C_CERT (PARENTNUMBER ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.CODE_IND with DBMS_METADATA attempting internal generator.
CREATE INDEX CODE_IND ON EV_ACTION (CODE ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.GROUP_ACTION_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GROUP_ACTION_PK ON EV_GROUP_ACTION (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.GROUP_VALUE_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX GROUP_VALUE_PK ON EV_GROUP_VALUE (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.ID with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ID ON PCH_COMPANY (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.ID_GROUP_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ID_GROUP_PK ON EV_GROUP (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.ID_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ID_PK ON EV_ACTION (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.ID_PRODUCT with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ID_PRODUCT ON PCH_PRODUCT (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.ID_PURCHASE with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ID_PURCHASE ON PCH_PURCHASE (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.IDX_DATACERT with DBMS_METADATA attempting internal generator.
CREATE INDEX IDX_DATACERT ON C_CERT (DATACERT ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.REPORT_MARK_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX REPORT_MARK_PK ON EV_REPORT_MARK (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.REPORT_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX REPORT_PK ON EV_REPORT (ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.SYS_C006997 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C006997 ON C_OTD (ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.SYS_C007001 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C007001 ON C_CERT (CERT_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.SYS_C007006 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C007006 ON C_COUNTRY (COUNTRY_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object BELTPP.SYS_C007010 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C007010 ON C_PRODUCT (PRODUCT_ID ASC) 
LOGGING 
TABLESPACE BELTPP 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
