REM INSERTING into BELTPP.C_COUNTRY
SET DEFINE OFF;
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Австралия','AU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Австрия','AT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Азербайджан','AZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Албания','AL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Алжир','DZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ангола','AO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Андорра','AD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Антигуа и Барбуда','AG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Аргентина','AR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Армения','AM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Афганистан','AF');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Багамские Острова','BS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бангладеш','BD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Барбадос','BB');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бахрейн','BH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Белиз','BZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Белорусь','BY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бельгия','BE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бенин','BJ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Болгария','BG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Боливия','BO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Босния и Герцеговина','BA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ботсвана','BW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бразилия','BR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бруней','BN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Буркина-Фасо','BF');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бурунди','BI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Бутан','BT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Вануату','VU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ватикан','VA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Великобритания','GB');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Венгрия','HU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Венесуэла','VE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Восточный Тимор','TL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Вьетнам','VN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Габон','GA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гаити','HT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гайана','GY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гамбия','GM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гана','GH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гватемала','GT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гвинея','GN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гвинея-Бисау','GW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Германия','DE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гондурас','HN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Гренада','GD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Греция','GR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Грузия','GE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Дания','DK');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Джибути','DJ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Доминика','DM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Доминиканская Республика','DO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' ДР Конго','CD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Египет','EG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Замбия','ZM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Зимбабве','ZW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Израиль','IL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Индия','IN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Индонезия','ID');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Иордания','JO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ирак','IQ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Иран','IR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ирландия','IE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Исландия','IS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Испания','ES');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Италия','IT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Йемен','YE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кабо-Верде','CV');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Казахстан','KZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Камбоджа','KH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Камерун','CM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Канада','CA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Катар','QA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кения','KE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кипр','CY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Киргизия','KG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кирибати','KI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Китай','CN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' КНДР','KP');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Колумбия','CO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Коморские Острова','KM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Коста-Рика','CR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кот-дИвуар','CI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Куба','CU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Кувейт','KW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Лаос','LA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Латвия','LV');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Лесото','LS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Либерия','LR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ливан','LB');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ливия','LY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Литва','LT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Лихтенштейн','LI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Люксембург','LU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Маврикий','MU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мавритания','MR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мадагаскар','MG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Македония','MK');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Малави','MW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Малайзия','MY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мали','ML');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мальдивские Острова','MV');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мальта','MT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Марокко','MA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Маршалловы Острова','MH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мексика','MX');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мозамбик','MZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Молдавия','MD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Монако','MC');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Монголия','MN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Мьянма','MM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Намибия','NA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Науру','NR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Непал','NP');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Нигер','NE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Нигерия','NG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Нидерланды','NL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Никарагуа','NI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Новая Зеландия','NZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Норвегия','NO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' ОАЭ','AE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Оман','OM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Пакистан','PK');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Палау','PW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Панама','PA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Папуа - Новая Гвинея','PG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Парагвай','PY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Перу','PE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Польша','PL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Португалия','PT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Республика Конго','CG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Республика Корея','KR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Россия','RU');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Руанда','RW');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Румыния','RO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сальвадор','SV');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Самоа','WS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сан-Марино','SM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сан-Томе и Принсипи','ST');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Саудовская Аравия','SA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Свазиленд','SZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сейшельские Острова','SC');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сенегал','SN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сент-Винсент и Гренадины','VC');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сент-Китс и Невис','KN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сент-Люсия','LC');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сербия','RS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сингапур','SG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сирия','SY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Словакия','SK');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Словения','SI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Соломоновы Острова','SB');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сомали','SO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Судан','SD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Суринам','SR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' США','US');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Сьерра-Леоне','SL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Таджикистан','TJ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Таиланд','TH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Танзания','TZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Того','TG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Тонга','TO');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Тринидад и Тобаго','TT');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Тувалу','TV');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Тунис','TN');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Туркмения','TM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Турция','TR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Уганда','UG');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Узбекистан','UZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Украина','UA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Уругвай','UY');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Федеративные Штаты Микронезии','FM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Фиджи','FJ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Филиппины','PH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Финляндия','FI');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Франция','FR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Хорватия','HR');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' ЦАР','CF');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Чад','TD');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Черногория','ME');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Чехия','CZ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Чили','CL');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Швейцария','CH');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Швеция','SE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Шри-Ланка','LK');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Эквадор','EC');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Экваториальная Гвинея','GQ');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Эритрея','ER');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Эстония','EE');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Эфиопия','ET');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' ЮАР','ZA');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Южная Осетия','OS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Южный Судан','SS');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Ямайка','JM');
Insert into BELTPP.C_COUNTRY (NAME,CODE) values (' Япония','JP');
