--------------------------------------------------------
--  File created - понедельник-Ноябрь-03-2014   
--------------------------------------------------------
REM INSERTING into BELTPP.C_OTD
SET DEFINE OFF;
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (1,'Минское отделение БелТПП','minsk','220113','Минск','Я.Колоса','65',null,'+375 17 2884922',null,'The Minsk Branch of Chamber of Commerce and Industry','Minsk','Y. Kolosa');
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (2,'Бресткое отделение БелТПП','brest','224030','Брест','ул. Гоголя','13',null,null,null,'The Brest Branch of Chamber of Commerce and Industry','Brest','Gogol');
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (3,'Витебское отделение БелТПП','vitebsk','210001','Витебск','ул. Космонавтов','4',null,null,null,'The Vitebsk Branch of Chamber of Commerce and Industry','Vitebsk','Kosmonavtov');
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (4,'Гомельское отделение БелТПП','gomel','246017','Гомель','ул. Ирининская','21',null,null,null,'The Gomel Branch of Chamber of Commerce and Industry','Gomel','Irininskay');
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (5,'Гродненское отделение БелТПП','grodno','230023','Гродно','ул. Советская','23а',null,null,null,'The Grodno Branch of Chamber of Commerce and Industry','Grodno','Sovietskaya');
Insert into C_OTD (ID,OTD_NAME,NAME_SYN,OTD_ADDR_INDEX,OTD_ADDR_CITY,OTD_ADDR_LINE,OTD_ADDR_BUILDING,OTD_ADDR_OFFICE,WORK_PHONE,CELL_PHONE,EOTD_NAME,EOTD_ADDR_CITY,EOTD_ADDR_LINE) values (6,'Могилевское отделение БелТПП','mogilev','212030','Могилев','улю Первомайская','71','802','+375 222 32 68 50',null,'The Mogilev Branch of Chamber of Commerce and Industry','Mogilev','Pervomayaskay');