--------------------------------------------------------
--  File created - Wednesday-October-29-2014   
--------------------------------------------------------
@D:\java\beltpp\SEQUENCES\CERT_ID_SEQ.sql
@D:\java\beltpp\SEQUENCES\DEMO_CUST_SEQ.sql
@D:\java\beltpp\SEQUENCES\DEMO_ORDER_ITEMS_SEQ.sql
@D:\java\beltpp\SEQUENCES\DEMO_ORD_SEQ.sql
@D:\java\beltpp\SEQUENCES\DEMO_PROD_SEQ.sql
@D:\java\beltpp\SEQUENCES\DEMO_USERS_SEQ.sql
@D:\java\beltpp\SEQUENCES\FILE_ID_SEQ.sql
@D:\java\beltpp\SEQUENCES\ID_ACTION_SEQ.sql
@D:\java\beltpp\SEQUENCES\ID_PURCHASE_SEQ.sql
@D:\java\beltpp\SEQUENCES\ID_REPORT_SEQ.sql
@D:\java\beltpp\SEQUENCES\ID_ROW_SEQ.sql
@D:\java\beltpp\SEQUENCES\PRODUCT_ID_SEQ.sql
@D:\java\beltpp\TABLES\C_CERT.sql
@D:\java\beltpp\TABLES\C_COUNTRY.sql
@D:\java\beltpp\TABLES\C_FILES_IN.sql
@D:\java\beltpp\TABLES\C_FILES_OUT.sql
@D:\java\beltpp\TABLES\C_OTD.sql
@D:\java\beltpp\TABLES\C_PRODUCT.sql
@D:\java\beltpp\TABLES\C_PRODUCT_DENORM.sql
@D:\java\beltpp\TABLES\EV_ACTION.sql
@D:\java\beltpp\TABLES\EV_GROUP.sql
@D:\java\beltpp\TABLES\EV_GROUP_ACTION.sql
@D:\java\beltpp\TABLES\EV_GROUP_VALUE.sql
@D:\java\beltpp\TABLES\EV_REPORT.sql
@D:\java\beltpp\TABLES\EV_REPORT_MARK.sql
@D:\java\beltpp\TABLES\EV_REPORT_ROW.sql
@D:\java\beltpp\TABLES\EV_REPORT_VALUE.sql
@D:\java\beltpp\TABLES\PCH_COMPANY.sql
@D:\java\beltpp\TABLES\PCH_PRODUCT.sql
@D:\java\beltpp\TABLES\PCH_PURCHASE.sql
@D:\java\beltpp\VIEWS\CERT_CHILD_VIEW.sql
@D:\java\beltpp\VIEWS\CERT_PARENT_VIEW.sql
@D:\java\beltpp\VIEWS\CERT_VIEW.sql
@D:\java\beltpp\VIEWS\CERT_VIEW_TOFILE.sql
@D:\java\beltpp\INDEXES\CERT_NUMBER_IDX.sql
@D:\java\beltpp\INDEXES\CERT_PARENTNUMBER_IDX.sql
@D:\java\beltpp\INDEXES\CODE_IND.sql
@D:\java\beltpp\INDEXES\C_COUNTRY_PK.sql
@D:\java\beltpp\INDEXES\GROUP_ACTION_PK.sql
@D:\java\beltpp\INDEXES\GROUP_VALUE_PK.sql
@D:\java\beltpp\INDEXES\ID.sql
@D:\java\beltpp\INDEXES\ID_GROUP_PK.sql
@D:\java\beltpp\INDEXES\ID_PK.sql
@D:\java\beltpp\INDEXES\ID_PRODUCT.sql
@D:\java\beltpp\INDEXES\ID_PURCHASE.sql
@D:\java\beltpp\INDEXES\REPORT_MARK_PK.sql
@D:\java\beltpp\INDEXES\REPORT_PK.sql
@D:\java\beltpp\INDEXES\SYS_C006997.sql
@D:\java\beltpp\INDEXES\SYS_C007001.sql
@D:\java\beltpp\INDEXES\SYS_C007010.sql
@D:\java\beltpp\CONSTRAINTS\C_CERT.sql
@D:\java\beltpp\CONSTRAINTS\C_COUNTRY.sql
@D:\java\beltpp\CONSTRAINTS\C_OTD.sql
@D:\java\beltpp\CONSTRAINTS\C_PRODUCT.sql
@D:\java\beltpp\CONSTRAINTS\EV_ACTION.sql
@D:\java\beltpp\CONSTRAINTS\EV_GROUP.sql
@D:\java\beltpp\CONSTRAINTS\EV_GROUP_ACTION.sql
@D:\java\beltpp\CONSTRAINTS\EV_GROUP_VALUE.sql
@D:\java\beltpp\CONSTRAINTS\EV_REPORT.sql
@D:\java\beltpp\CONSTRAINTS\EV_REPORT_MARK.sql
@D:\java\beltpp\CONSTRAINTS\EV_REPORT_ROW.sql
@D:\java\beltpp\CONSTRAINTS\PCH_COMPANY.sql
@D:\java\beltpp\CONSTRAINTS\PCH_PRODUCT.sql
@D:\java\beltpp\CONSTRAINTS\PCH_PURCHASE.sql
@D:\java\beltpp\REF_CONSTRAINTS\C_CERT.sql
@D:\java\beltpp\REF_CONSTRAINTS\C_PRODUCT.sql
@D:\java\beltpp\REF_CONSTRAINTS\EV_GROUP_ACTION.sql
@D:\java\beltpp\REF_CONSTRAINTS\EV_GROUP_VALUE.sql
@D:\java\beltpp\REF_CONSTRAINTS\PCH_PRODUCT.sql
@D:\java\beltpp\REF_CONSTRAINTS\PCH_PURCHASE.sql
@D:\java\beltpp\FUNCTIONS\CUSTOM_AUTH.sql
@D:\java\beltpp\FUNCTIONS\CUSTOM_HASH.sql
