
-------------------------------------------------------
--  File created - среда-Март-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FS_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "BELTPP"."FS_TEMPLATE" 
   (	"KEY" VARCHAR2(50 BYTE), 
	"RU" VARCHAR2(1024 BYTE), 
	"EN" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BELTPP.FS_TEMPLATE
SET DEFINE OFF;
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('submission','Выдан для предоставления в','For submission to ');
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('confirmation','Настоящим удостоверяем, основываясь на представленных сведениях, что товары, перечисленные ниже, производятся [producer],  не имеют ограничений для обращения на территории Республики Беларусь. Насколько нам известно, нет никаких запретов на экспорт этих товаров','Referring to the information provided, the undersigned hereby declares that the products listed below are manufactured by [producer] and are available for free sale in the Republic of Belarus. To the best of our knowledge, there are no prohibitions against the export of these products.');
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('listofproducts','Перечень товаров:','List of products');
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('listscount','Продолжение перечня товаров смотри в приложении на [listscount] листах','For a continued list of products see Annex (total sheets - [listscount])   ');
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('declaration','Данный сертификат не является явной или подразумеваемой гарантией для какого-либо товара вышеуказанного производителя и (или) экспортера. Сертификат не должен использоваться для целей рекламы или подобных целей, не является документом по оценке соответствия и не подтверждает происхождение товара из Республики Беларусь.','This certificate should not be interpreted as a guarantee, explicit or implied for any of the products of the manufacturer and (or) exporter mentioned above. Neither should it be used for advertising or similar purposes. This certificate is not a compliance verification document. This certificate is not a certificate of origin.');
Insert into BELTPP.FS_TEMPLATE (KEY,RU,EN) values ('valid','Срок действия с [datestart]  по [dateexpiry] включительно.','Valid from [datestart] till [dateexpiry] inclusive.');




--------------------------------------------------------
--  File created - четверг-Март-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CCI_DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "BELTPP"."CCI_DEPARTMENT" 
   (	"ID" NUMBER, 
	"ID_PARENT" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"ID_OTD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CCI_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BELTPP"."CCI_EMPLOYEE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"RUNAME" VARCHAR2(120 BYTE), 
	"RUJOB" VARCHAR2(120 BYTE), 
	"ID_DEPARTMENT" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"ENNAME" VARCHAR2(20 BYTE), 
	"ENJOB" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"BDAY" DATE, 
	"ACTIVE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CCI_DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."CCI_DEPARTMENT_PK" ON "BELTPP"."CCI_DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CCI_EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."CCI_EMPLOYEE_PK" ON "BELTPP"."CCI_EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CCI_DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."CCI_DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."CCI_DEPARTMENT" ADD CONSTRAINT "CCI_DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BELTPP"."CCI_EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."CCI_EMPLOYEE" ADD CONSTRAINT "CCI_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BELTPP"."CCI_EMPLOYEE" MODIFY ("RUJOB" NOT NULL ENABLE);
