--------------------------------------------------------
--  File created - С‡РµС‚РІРµСЂРі-Р¤РµРІСЂР°Р»СЊ-16-2017   
--------------------------------------------------------
DROP TABLE "FS_BLANK";
DROP TABLE "FS_PRODUCT";
DROP TABLE "FS_CERT";
DROP TABLE "CCI_EMPLOYEE";
DROP TABLE "FS_BRANCH";
--------------------------------------------------------
--  DDL for Table CCI_CLIENT
--------------------------------------------------------


  CREATE TABLE "CCI_EMPLOYEE" 
  (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(120 BYTE), 
	"JOB" VARCHAR2(120 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table FS_BLANK
--------------------------------------------------------

  CREATE TABLE "FS_BLANK" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"ID_FSCERT" NUMBER, 
	"PAGE" NUMBER, 
	"BLANKNUMBER" VARCHAR2(20 BYTE)
   );
--------------------------------------------------------
--  DDL for Table FS_BRANCH
--------------------------------------------------------

  CREATE TABLE "FS_BRANCH" 
  (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"NAME" VARCHAR2(2000 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"LINE" VARCHAR2(200 BYTE), 
	"CINDEX" VARCHAR2(200 BYTE), 
	"OFFICE" VARCHAR2(200 BYTE), 
	"BUILDING" VARCHAR2(200 BYTE), 
	"WORK_PHONE" VARCHAR2(50 BYTE), 
	"CELL_PHONE" VARCHAR2(50 BYTE), 
	"UNP" VARCHAR2(30 BYTE), 
	"OKPO" VARCHAR2(30 BYTE), 
	"BNAME" VARCHAR2(2000 BYTE), 
	"BCITY" VARCHAR2(200 BYTE), 
	"BLINE" VARCHAR2(200 BYTE), 
	"BINDEX" VARCHAR2(20 BYTE), 
	"BOFFICE" VARCHAR2(20 BYTE), 
	"BBUILDING" VARCHAR2(20 BYTE), 
	"ACCOUNT" VARCHAR2(50 BYTE), 
	"BUNP" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"BEMAIL" VARCHAR2(20 BYTE), 
	"CODECOUNTRY" VARCHAR2(20 BYTE), 
	"BCODECOUNTRY" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table FS_CERT
--------------------------------------------------------

  CREATE TABLE "FS_CERT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE, 
	"CERTNUMBER" VARCHAR2(20 BYTE), 
	"PARENTNUMBER" VARCHAR2(20 BYTE), 
	"DATEISSUE" DATE, 
	"DATEEXPIRY" DATE, 
	"CONFIRMATION" VARCHAR2(2000 BYTE), 
	"DECLARATION" VARCHAR2(2000 BYTE), 
	"ID_BRANCH" NUMBER, 
	"ID_EXPORTER" NUMBER, 
	"ID_PRODUCER" NUMBER, 
	"ID_EXPERT" NUMBER, 
	"ID_SIGNER" NUMBER,
	"DATECERT" DATE, 
	"CODECOUNTRYTARGET" VARCHAR2(3 BYTE), 
	"OTD_ID" NUMBER, 
	"LISTCOUNT" NUMBER

   );
--------------------------------------------------------
--  DDL for Table FS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "FS_PRODUCT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ID_FSCERT" NUMBER, 
	"NUMERATOR" NUMBER, 
	"TOVAR" VARCHAR2(2000 BYTE)
   ) ;


--------------------------------------------------------
--  DDL for Index CCI_EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CCI_EMPLOYEE_PK" ON "CCI_EMPLOYEE" ("ID");
--------------------------------------------------------
--  DDL for Index FS_BLANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_BLANK_PK" ON "FS_BLANK" ("ID")  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_NAME
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_NAME" ON "FS_BRANCH" ("NAME");
--------------------------------------------------------
--  DDL for Index FS_BRANCH_LINE
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_LINE" ON "FS_BRANCH" ("LINE");
  
--------------------------------------------------------
--  DDL for Index FS_BRANCH_OFFICE
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_OFFICE" ON "FS_BRANCH" ("OFFICE");
--------------------------------------------------------
--  DDL for Index FS_BRANCH_INDEX
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_INDEX" ON "FS_BRANCH" ("CINDEX");
--------------------------------------------------------
--  DDL for Index FS_BRANCH_BUILDING
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_BUILDING" ON "FS_BRANCH" ("BUILDING")   ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_BRANCH_PK" ON "FS_BRANCH" ("ID") ;
--------------------------------------------------------
--  DDL for Index FS_CERT_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_CERT_NUMBER" ON "FS_CERT" ("CERTNUMBER");
--------------------------------------------------------
--  DDL for Index FS_CERT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_CERT_PK" ON "FS_CERT" ("ID") ;
--------------------------------------------------------
--  DDL for Index FS_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_PRODUCT_PK" ON "FS_PRODUCT" ("ID") ;
--------------------------------------------------------
--  Constraints for Table CCI_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CCI_EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CCI_EMPLOYEE" ADD CONSTRAINT "CCI_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_BLANK
--------------------------------------------------------

  ALTER TABLE "FS_BLANK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_BLANK" MODIFY ("PAGE" NOT NULL ENABLE);
  ALTER TABLE "FS_BLANK" ADD CONSTRAINT "FS_BLANK_PK" PRIMARY KEY ("ID")
  USING INDEX ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_BRANCH
--------------------------------------------------------

  ALTER TABLE "FS_BRANCH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_BRANCH" ADD CONSTRAINT "FS_BRANCH_PK" PRIMARY KEY ("ID")
  USING INDEX   ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_CERT
--------------------------------------------------------

  ALTER TABLE "FS_CERT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_CERT" MODIFY ("CERTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "FS_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_PRODUCT" ADD CONSTRAINT "FS_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX   ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FS_BLANK
--------------------------------------------------------

  ALTER TABLE "FS_BLANK" ADD CONSTRAINT "FS_BLANK_FK1" FOREIGN KEY ("ID_FSCERT")
	  REFERENCES "FS_CERT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FS_CERT
--------------------------------------------------------

  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_FK_BRANCH" FOREIGN KEY ("ID_BRANCH")
	  REFERENCES "FS_BRANCH" ("ID") ENABLE;
  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_FK_EXPERT" FOREIGN KEY ("ID_EXPERT")
	  REFERENCES "CCI_EMPLOYEE" ("ID") ENABLE;
  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_FK_EXPORTER" FOREIGN KEY ("ID_EXPORTER")
	  REFERENCES "CCI_CLIENT" ("ID") ENABLE;
  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_FK_PRODUCER" FOREIGN KEY ("ID_PRODUCER")
	  REFERENCES "CCI_CLIENT" ("ID") ENABLE;
  ALTER TABLE "FS_CERT" ADD CONSTRAINT "FS_CERT_FK_SINGER" FOREIGN KEY ("ID_SIGNER")
	  REFERENCES "CCI_EMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "FS_PRODUCT" ADD CONSTRAINT "FS_PRODUCT_FK_FSCERT" FOREIGN KEY ("ID_FSCERT")
	  REFERENCES "FS_CERT" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger FS_BLANK_TRG
--------------------------------------------------------

	  
CREATE OR REPLACE FORCE EDITIONABLE VIEW "FSCERTVIEW" ("ID", "CERTNUMBER", "PARENTNUMBER", "DATEISSUE", "DATEEXPIRY", "CONFIRMATION", "DECLARATION", "ID_BRANCH", "ID_EXPORTER", "ID_PRODUCER", "ID_EXPERT", "ID_SIGNER", "DATECERT", "CODECOUNTRYTARGET", "OTD_ID", "LISTSCOUNT", "BRANCHNAME", "BRANCHADDRESS", "EXPORTERNAME", "EXPORTERADDRESS", "PRODUCERNAME", "PRODUCERADDRESS", "EXPERTNAME", "SIGNERNAME", "JOB", "COUNTRYNAME") AS 
  select a."ID",a."CERTNUMBER",a."PARENTNUMBER",a."DATEISSUE",a."DATEEXPIRY",a."CONFIRMATION",a."DECLARATION",a."ID_BRANCH",a."ID_EXPORTER",a."ID_PRODUCER",a."ID_EXPERT",a."ID_SIGNER",a."DATECERT",a."CODECOUNTRYTARGET",a."OTD_ID",a."LISTSCOUNT", b.name branchname, b.cindex||', '||b.city||', '||b.line||', '||b.building||', '||b.office branchaddress,  
c.name exportername, c.cindex||', '||c.city||', '||c.line||', '||c.building||', '||c.office exporteraddress,  
c.name producername, d.cindex||', '||d.city||', '||d.line||', '||d.building||', '||d.office produceraddress,  
e.name expertname, f.name signername, f.job job, g.name countryname
from fs_cert a
left join fs_branch b on a.ID_BRANCH = b.id
left join cci_client c on a.ID_EXPORTER = c.id
left join cci_client d on a.ID_Producer = d.id
left join cci_employee e on a.ID_EXPERT = e.id
left join cci_employee f on a.ID_SIGNER = f.id
left join c_country g on a.codecountrytarget = g.code;
	  
========================================================================
select id from fs_cert where id_branch in (select id from fs_branch where name like '%Минск%') 
and id_exporter in (select id from cci_client where name like '%Рога%')
and id_producer in (select id from cci_client where name like '%Мо%')
and id in (select id_fscert from fs_product where tovar like '%ВГА%')
and id in (select id from cci_employee where name like '%о%')
and certnumber like '%009%';
	  


======================================================================================
-