--------------------------------------------------------
--  File created - четверг-Февраль-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CCI_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BELTPP"."CCI_EMPLOYEE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(120 BYTE), 
	"JOB" VARCHAR2(120 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table FS_BLANK
--------------------------------------------------------

  CREATE TABLE "BELTPP"."FS_BLANK" 
   (	"ID" NUMBER, 
	"ID_FSCERT" NUMBER, 
	"PAGE" NUMBER, 
	"BLANKNUMBER" VARCHAR2(20 BYTE)
   );
--------------------------------------------------------
--  DDL for Table FS_CERT
--------------------------------------------------------

  CREATE TABLE "BELTPP"."FS_CERT" 
   (	"ID" NUMBER, 
	"CERTNUMBER" VARCHAR2(20 BYTE), 
	"PARENTNUMBER" VARCHAR2(20 BYTE), 
	"DATEISSUE" DATE, 
	"DATEEXPIRY" DATE, 
	"CONFIRMATION" VARCHAR2(2000 BYTE), 
	"DECLARATION" VARCHAR2(2000 BYTE), 
	"ID_BRANCH" NUMBER, 
	"ID_EXPORTER" NUMBER, 
	"ID_PRODUCER" NUMBER, 
	"ID_EXPERT" NUMBER, 
	"ID_SIGNER" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table FS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "BELTPP"."FS_PRODUCT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ID_FSCERT" NUMBER, 
	"NUMERATOR" NUMBER, 
	"TOVAR" VARCHAR2(2000 BYTE)
   ) ;
   
   
--------------------------------------------------------
--  DDL for Index CCI_CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."CCI_CLIENT_PK" ON "BELTPP"."CCI_CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CCI_EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."CCI_EMPLOYEE_PK" ON "BELTPP"."CCI_EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FS_BLANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."FS_BLANK_PK" ON "BELTPP"."FS_BLANK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FS_CERT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."FS_CERT_PK" ON "BELTPP"."FS_CERT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FS_CERT_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "BELTPP"."FS_CERT_NUMBER" ON "BELTPP"."FS_CERT" ("CERTNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CCI_CLIENT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."CCI_CLIENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."CCI_CLIENT" ADD CONSTRAINT "CCI_CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BELTPP"."CCI_EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."CCI_EMPLOYEE" ADD CONSTRAINT "CCI_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_BLANK
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_BLANK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."FS_BLANK" MODIFY ("PAGE" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."FS_BLANK" ADD CONSTRAINT "FS_BLANK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_CERT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_CERT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."FS_CERT" MODIFY ("CERTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FS_BLANK
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_BLANK" ADD CONSTRAINT "FS_BLANK_FK1" FOREIGN KEY ("ID_FSCERT")
	  REFERENCES "BELTPP"."FS_CERT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FS_CERT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_FK_BRANCH" FOREIGN KEY ("ID_BRANCH")
	  REFERENCES "BELTPP"."C_OTD" ("ID") ENABLE;
  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_FK_EXPERT" FOREIGN KEY ("ID_EXPERT")
	  REFERENCES "BELTPP"."CCI_EMPLOYEE" ("ID") ENABLE;
  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_FK_EXPORTER" FOREIGN KEY ("ID_EXPORTER")
	  REFERENCES "BELTPP"."CCI_CLIENT" ("ID") ENABLE;
  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_FK_PRODUCER" FOREIGN KEY ("ID_PRODUCER")
	  REFERENCES "BELTPP"."CCI_CLIENT" ("ID") ENABLE;
  ALTER TABLE "BELTPP"."FS_CERT" ADD CONSTRAINT "FS_CERT_FK_SINGER" FOREIGN KEY ("ID_SIGNER")
	  REFERENCES "BELTPP"."CCI_EMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "BELTPP"."FS_PRODUCT" ADD CONSTRAINT "FS_PRODUCT_FK1" FOREIGN KEY ("ID_FSCERT")
	  REFERENCES "BELTPP"."FS_CERT" ("ID") ENABLE;
