--------------------------------------------------------
--  File created - РїСЏС‚РЅРёС†Р°-РњР°СЂС‚-31-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CCI_CLIENT
--------------------------------------------------------

  DROP TABLE "CCI_CLIENT";
  DROP TABLE "CCI_CLIENT_LOCALE";
  DROP TABLE "CCI_EMPLOYEE";
  DROP TABLE "CCI_EMPLOYEE_LOCALE";
  DROP TABLE "FS_BRANCH_LOCALE";
  
  
  
  CREATE TABLE "CCI_CLIENT" 
   ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ,, 
	"NAME" VARCHAR2(200), 
	"CITY" VARCHAR2(200), 
	"STREET" VARCHAR2(200), 
	"CINDEX" VARCHAR2(200), 
	"OFFICE" VARCHAR2(200), 
	"BUILDING" VARCHAR2(200), 
	"PHONE" VARCHAR2(50), 
	"CELL" VARCHAR2(50),
    "FAX" VARCHAR2(50)	
	"UNP" VARCHAR2(30), 
	"OKPO" VARCHAR2(30), 
	"BNAME" VARCHAR2(200), 
	"BCITY" VARCHAR2(200), 
	"BSTREET" VARCHAR2(200), 
	"BINDEX" VARCHAR2(20), 
	"BOFFICE" VARCHAR2(20), 
	"BBUILDING" VARCHAR2(20), 
	"ACCOUNT" VARCHAR2(50), 
	"BUNP" VARCHAR2(50), 
	"EMAIL" VARCHAR2(80), 
	"BEMAIL" VARCHAR2(20), 
	"CODECOUNTRY" VARCHAR2(20), 
	"BCODECOUNTRY" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(512), 
	"VERSION" NUMBER DEFAULT 0, 
	"LOCKED" NUMBER(1,0) DEFAULT 0 
   ) ;
--------------------------------------------------------
--  DDL for Table CCI_CLIENT_LOCALE
--------------------------------------------------------

  CREATE TABLE "CCI_CLIENT_LOCALE" 
   ("IDCLIENT" NUMBER, 
	"NAME" VARCHAR2(1000), 
	"STREET" VARCHAR2(1000), 
	"CITY" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(1000), 
	"LOCALE" VARCHAR2(2)
   ) ;
--------------------------------------------------------
--  DDL for Table CCI_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "CCI_EMPLOYEE" 
   ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(120), 
	"JOB" VARCHAR2(120), 
	"ID_DEPARTMENT" NUMBER, 
	"FIRSTNAME" VARCHAR2(50), 
	"LASTNAME" VARCHAR2(50), 
	"MIDDLENAME" VARCHAR2(50), 
	"PHONE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(20), 
	"BDAY" DATE, 
	"ACTIVE" CHAR(1) DEFAULT 'Y'
   ) ;
--------------------------------------------------------
--  DDL for Table CCI_EMPLOYEE_LOCALE
--------------------------------------------------------

  CREATE TABLE "CCI_EMPLOYEE_LOCALE" 
   ("IDEMPLOYEE" NUMBER, 
	"LOCALE" VARCHAR2(2), 
	"NAME" VARCHAR2(200), 
	"JOB" VARCHAR2(200)
   ) ;
--------------------------------------------------------
--  DDL for Table FS_BRANCH
--------------------------------------------------------

  CREATE TABLE "FS_BRANCH" 
   ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(2000), 
	"CITY" VARCHAR2(200), 
	"LINE" VARCHAR2(200), 
	"CINDEX" VARCHAR2(200), 
	"OFFICE" VARCHAR2(200), 
	"BUILDING" VARCHAR2(200), 
	"PHONE" VARCHAR2(50), 
	"CELL" VARCHAR2(50),
	"FAX" VARCHAR2(50),	
	"UNP" VARCHAR2(30), 
	"OKPO" VARCHAR2(30), 
	"BNAME" VARCHAR2(2000), 
	"BCITY" VARCHAR2(200), 
	"BSTREET" VARCHAR2(200), 
	"BINDEX" VARCHAR2(20), 
	"BOFFICE" VARCHAR2(20), 
	"BBUILDING" VARCHAR2(20), 
	"ACCOUNT" VARCHAR2(50), 
	"BUNP" VARCHAR2(50), 
	"EMAIL" VARCHAR2(80), 
	"BEMAIL" VARCHAR2(20), 
	"CODECOUNTRY" VARCHAR2(20), 
	"BCODECOUNTRY" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(512), 
	"VERSION" NUMBER DEFAULT 0, 
	"LOCKED" NUMBER(1,0) DEFAULT 0
   ) ;
--------------------------------------------------------
--  DDL for Table FS_BRANCH_LOCALE
--------------------------------------------------------

  CREATE TABLE "FS_BRANCH_LOCALE" 
   ("IDBRANCH" NUMBER, 
	"LOCALE" VARCHAR2(2), 
	"NAME" VARCHAR2(1000), 
	"CITY" VARCHAR2(120), 
	"STREET" VARCHAR2(120), 
	"ADDRESS" VARCHAR2(1000)
   ) ;
--------------------------------------------------------
--  DDL for Table FS_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "FS_TEMPLATE" 
   ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , ,
    "KEY" VARCHAR2(50), 
	"TEXT" VARCHAR2(2024), 
   ) ;
--------------------------------------------------------
--  DDL for Table FS_TEMPLATE_LOCALE
--------------------------------------------------------

  CREATE TABLE "FS_TEMPLATE_LOCALE" 
   ("IDKEY" NUMBER, 
	"LOCALE" VARCHAR2(2), 
	"TEXT" VARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for View CLIENT_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "CLIENT_VIEW" ("ID", "NAME", "CITY", "STREET", "CINDEX", "OFFICE", "BUILDING", "PHONE", "CELL", "FAX", "UNP", "OKPO", "BNAME", "BCITY", "BSTREET", "BINDEX", "BOFFICE", "BBUILDING", "ACCOUNT", "BUNP", "EMAIL", "BEMAIL", "CODECOUNTRY", "BCODECOUNTRY", "ADDRESS", "VERSION", "LOCKED", "COUNTRY", "BCOUNTRY") AS 
  SELECT  cl."ID",cl."NAME", cl."CITY",cl."STREET",cl."CINDEX",cl."OFFICE",cl."BUILDING",cl."PHONE",cl."CELL", cl."FAX", cl."UNP",cl."OKPO",cl."BNAME",cl."BCITY",cl."BSTREET",cl."BINDEX",cl."BOFFICE",cl."BBUILDING",cl."ACCOUNT",cl."BUNP",cl."EMAIL",cl."BEMAIL",cl."CODECOUNTRY",cl."BCODECOUNTRY", cl."ADDRESS", cl."VERSION", cl."LOCKED", cc.name as country, cb.name as bcountry  
FROM CCI_CLIENT cl 
LEFT JOIN C_COUNTRY cc ON cl.codecountry = cc.code 
LEFT JOIN C_COUNTRY cb ON cl.bcodecountry = cb.code;
--------------------------------------------------------
--  DDL for Index CCI_CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CCI_CLIENT_PK" ON "CCI_CLIENT" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index CCI_EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CCI_EMPLOYEE_PK" ON "CCI_EMPLOYEE" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_NAME
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_NAME" ON "FS_BRANCH" ("NAME") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_LINE
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_STREET" ON "FS_BRANCH" ("STREET") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_OFFICE
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_OFFICE" ON "FS_BRANCH" ("OFFICE") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_INDEX
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_INDEX" ON "FS_BRANCH" ("CINDEX") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_BUILDING
--------------------------------------------------------

  CREATE INDEX "FS_BRANCH_BUILDING" ON "FS_BRANCH" ("BUILDING") 
  ;
--------------------------------------------------------
--  DDL for Index FS_BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_BRANCH_PK" ON "FS_BRANCH" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index FS_TEMPLATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FS_TEMPLATE_PK" ON "FS_TEMPLATE" ("ID") 
  ;
--------------------------------------------------------
--  Constraints for Table CCI_CLIENT
--------------------------------------------------------

  ALTER TABLE "CCI_CLIENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CCI_CLIENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CCI_CLIENT" ADD CONSTRAINT "CCI_CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCI_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CCI_EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CCI_EMPLOYEE" ADD CONSTRAINT "CCI_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "CCI_EMPLOYEE" MODIFY ("JOB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FS_BRANCH
--------------------------------------------------------

  ALTER TABLE "FS_BRANCH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_BRANCH" ADD CONSTRAINT "FS_BRANCH_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_TEMPLATE
--------------------------------------------------------

  ALTER TABLE "FS_TEMPLATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FS_TEMPLATE" ADD CONSTRAINT "FS_TEMPLATE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FS_TEMPLATE_LOCALE
--------------------------------------------------------

  ALTER TABLE "FS_TEMPLATE_LOCALE" MODIFY ("LOCALE" NOT NULL ENABLE);
